# 📁 test_generator.py
# 📂 保存場所: /src/utils/test_generator.py
"""
test_generator: pytest テストコード生成モジュール

生成方針:
- pytest ベースの関数名（test_ で始まる）
- if __name__ == "__main__": を書かない
- DB 接続を行わない
- ファイル書き込み I/O を行わない（必要なら mock を書くよう明示）
- 危険な操作（os.system, subprocess, eval, exec など）を禁止

安定化機能:
- LLM なしでも AST ベースでテンプレート生成可能（safe/template mode）
- LLM エラー時は自動的にテンプレートにフォールバック
- 環境変数で LLM の有効/無効を制御可能
"""

from __future__ import annotations

import ast
import logging
import os
from dataclasses import dataclass
from pathlib import Path

from dotenv import load_dotenv

try:
    from openai import OpenAI

    HAS_OPENAI = True
except ImportError:
    HAS_OPENAI = False
    OpenAI = None

from nexuscore.utils.test_utils import (
    create_fallback_test_file,
    extract_code_from_markdown,
    project_path_to_module_path,
    validate_test_code,
)

load_dotenv()
logger = logging.getLogger(__name__)

# クライアントは必要に応じて初期化（グローバルに持たない）
_client: OpenAI | None = None


@dataclass
class TestGenConfig:
    """
    test_generator の設定クラス

    Attributes:
        use_llm: LLM を使用するかどうか（False の場合は template mode のみ）
        max_functions: 1ファイルあたり最大何関数までテスト生成するか
        seed: ランダムシード（将来の拡張用）
    """

    use_llm: bool = True
    max_functions: int = 20
    seed: int | None = None


def _env_flag(name: str, default: bool) -> bool:
    """
    環境変数から bool 値を読み込む

    Args:
        name: 環境変数名
        default: デフォルト値

    Returns:
        環境変数が "0", "false", "no" のいずれかなら False、それ以外は True
    """
    v = os.getenv(name)
    if v is None:
        return default
    return v.lower() not in {"0", "false", "no"}


# デフォルト設定（環境変数から読み込み）
DEFAULT_CONFIG = TestGenConfig(
    use_llm=_env_flag("NEXUS_TESTGEN_ENABLE_LLM", True),
    max_functions=int(os.getenv("NEXUS_TESTGEN_MAX_FUNCTIONS", "20")),
    seed=None,
)


def _get_client() -> OpenAI:
    """OpenAI クライアントを取得（遅延初期化）"""
    global _client
    if _client is None:
        if not HAS_OPENAI:
            raise ImportError("openai package is not installed")
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
            raise ValueError("OPENAI_API_KEY environment variable is not set")
        _client = OpenAI(api_key=api_key)
    return _client


def generate_template_tests(
    module_path: Path,
    *,
    max_functions: int = 20,
    project_root: Path | None = None,
) -> str:
    """
    LLM を使わず、AST 解析だけで pytest 用のテストひな形を生成する。

    失敗しても例外は投げず、最低限のコメントを含むテストファイル文字列を返す。

    Args:
        module_path: 対象モジュールのパス
        max_functions: 最大関数数
        project_root: プロジェクトルート（import path 生成に使用）

    Returns:
        生成されたテストコード（テンプレート）
    """
    try:
        # ファイルを読み込み
        try:
            source_code = module_path.read_text(encoding="utf-8", errors="ignore")
        except Exception as e:
            logger.warning(f"Failed to read module {module_path}: {e}")
            return f'''# Auto-generated by NexusCore test_generator (template mode)
# NOTE: Failed to read module {module_path}. Please write tests manually.

import pytest


def test_auto_generated_test_scaffold_read_error():
    """Auto-generated test scaffold due to read error."""
    pytest.skip("Failed to read module: {e}")
'''

        # AST パース
        try:
            tree = ast.parse(source_code, filename=str(module_path))
        except SyntaxError as e:
            logger.warning(f"Failed to parse module {module_path}: {e}")
            return f'''# Auto-generated by NexusCore test_generator (template mode)
# NOTE: Failed to parse module {module_path}. Please write tests manually.

import pytest


def test_auto_generated_test_scaffold_parse_error():
    """Auto-generated test scaffold due to parse error."""
    pytest.skip("Failed to parse module: {e}")
'''

        # 関数名を収集
        function_names: list[str] = []
        class_methods: list[tuple[str, str]] = []  # (class_name, method_name)

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                # トップレベル関数
                if not any(
                    isinstance(parent, ast.ClassDef)
                    for parent in ast.walk(tree)
                    if hasattr(parent, "body") and node in getattr(parent, "body", [])
                ):
                    # 簡易チェック: 関数がクラス内にないことを確認
                    # より正確には、親ノードを辿る必要があるが、簡易実装
                    function_names.append(node.name)
            elif isinstance(node, ast.ClassDef):
                # クラス内メソッド
                for item in node.body:
                    if isinstance(item, ast.FunctionDef):
                        if not item.name.startswith("_"):  # プライベートメソッドは除外
                            class_methods.append((node.name, item.name))

        # max_functions でトリム
        all_functions = function_names[:max_functions]
        all_methods = class_methods[:max_functions]

        # import path の決定
        if project_root is not None:
            try:
                module_import_path = project_path_to_module_path(project_root, module_path)
            except Exception:
                module_import_path = module_path.stem
        else:
            module_import_path = module_path.stem

        # テストコード生成
        lines = [
            "# Auto-generated by NexusCore test_generator (template mode)",
            "",
            "import pytest",
            "",
        ]

        # インポート文
        if module_import_path:
            lines.append(f"from {module_import_path} import *  # TODO: adjust import path")
        lines.append("")

        # トップレベル関数のテスト
        for func_name in all_functions:
            lines.append(f"def test_{func_name}():")
            lines.append(f"    # TODO: implement test for {module_import_path}.{func_name}")
            lines.append('    assert False, "not implemented"')
            lines.append("")

        # クラスメソッドのテスト
        for class_name, method_name in all_methods:
            test_name = f"test_{class_name}_{method_name}"
            lines.append(f"def {test_name}():")
            lines.append(
                f"    # TODO: implement test for {module_import_path}.{class_name}.{method_name}"
            )
            lines.append('    assert False, "not implemented"')
            lines.append("")

        # 関数が0件の場合
        if not all_functions and not all_methods:
            lines.append("def test_auto_generated_test_scaffold_no_functions():")
            lines.append('    """Auto-generated test scaffold (no functions found)."""')
            lines.append('    pytest.skip("No functions found in module")')
            lines.append("")

        return "\n".join(lines)

    except Exception as e:
        # すべての例外をキャッチして、最低限のテストファイルを返す
        logger.error(f"Unexpected error in generate_template_tests: {e}", exc_info=True)
        return f'''# Auto-generated by NexusCore test_generator (template mode)
# NOTE: Failed to generate template for module {module_path}. Please write tests manually.

import pytest


def test_auto_generated_test_scaffold_error():
    """Auto-generated test scaffold due to unexpected error."""
    pytest.skip("Unexpected error during template generation: {e}")
'''


def _try_generate_tests_with_llm(
    template_code: str,
    code: str,
    config: TestGenConfig,
    file_path: Path | None = None,
    project_root: Path | None = None,
    module_path: str | None = None,
) -> str:
    """
    テンプレートコードをベースに LLM で肉付けしたテストコードを返す。

    失敗した場合は例外を投げず、入力の template_code をそのまま返す。

    Args:
        template_code: テンプレートコード
        code: テスト対象のコード
        config: 設定
        file_path: 対象ファイルのパス
        project_root: プロジェクトルート
        module_path: モジュールパス

    Returns:
        生成されたテストコード（失敗時は template_code をそのまま返す）
    """
    if not config.use_llm:
        return template_code

    try:
        # import path の決定
        if module_path is None and file_path is not None and project_root is not None:
            module_path = project_path_to_module_path(project_root, file_path)

        # プロンプトの構築
        prompt = f"""次のPythonコードに対して、pytest形式のユニットテストを生成してください。

# 対象コード
```python
{code}
```

# テンプレート（参考）
```python
{template_code}
```

# 絶対守ってほしい制約（必須）
1. pytest ベースの関数名（test_ で始まる）を使用してください
2. if __name__ == "__main__": を書かないでください
3. DB 接続を行わないでください（必要なら mock を使用）
4. ファイル書き込み I/O（open(..., "w"), open(..., "a")）を行わないでください（必要なら mock を使用）
5. 危険な操作（os.system, subprocess, eval, exec, __import__）を絶対に使用しないでください
6. 外部API依存は必ずモック化してください
7. time.sleep は使わないでください
8. ランダム値は固定してください

# 理想的なテスト例
```python
import pytest
from unittest.mock import Mock, patch, MagicMock

# モジュールパス: {module_path or "your_module"}

def test_function_name_normal_case():
    \"\"\"正常系のテスト\"\"\"
    # テストコード
    assert True

def test_function_name_edge_case():
    \"\"\"エッジケースのテスト\"\"\"
    # テストコード
    assert True

def test_function_name_error_case():
    \"\"\"異常系のテスト\"\"\"
    # テストコード
    with pytest.raises(ValueError):
        # エラーが発生するコード
        pass
```

# 出力形式（必須）
上記の例に従って、pytest テストコードを生成してください。
コードブロック（```python ... ```）で囲んで出力してください。
"""

        client = _get_client()
        response = client.chat.completions.create(
            model=os.getenv("OPENAI_MODEL", "gpt-4"),
            messages=[
                {
                    "role": "system",
                    "content": "あなたは優秀なPythonのテストエンジニアです。安全性と品質を最優先に、pytest形式のテストコードを生成します。",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
        )

        generated_code = response.choices[0].message.content
        if generated_code:
            return generated_code
        else:
            logger.warning("LLM returned empty response, falling back to template")
            return template_code

    except ImportError as e:
        logger.warning(f"OpenAI client not available: {e}, falling back to template")
        return template_code
    except ValueError as e:
        logger.warning(f"OpenAI API key not configured: {e}, falling back to template")
        return template_code
    except Exception as e:
        # HTTPError, Timeout, JSONDecodeError などすべての例外をキャッチ
        logger.warning(f"LLM generation failed: {e}, falling back to template", exc_info=True)
        return template_code


def generate_unit_tests(
    code: str,
    file_path: Path | None = None,
    project_root: Path | None = None,
    module_path: str | None = None,
    config: TestGenConfig | None = None,
) -> str:
    """
    Python コードに対して pytest 形式のユニットテストを生成する。

    LLM が使えない場合や失敗した場合は、AST ベースのテンプレートにフォールバックする。

    Args:
        code: テスト対象の Python コード
        file_path: 対象ファイルのパス（import path 生成に使用）
        project_root: プロジェクトルート（import path 生成に使用）
        module_path: モジュールパス（指定されている場合）
        config: 設定（None の場合は DEFAULT_CONFIG を使用）

    Returns:
        生成されたテストコード（Markdown コードブロックを含む可能性がある）
    """
    if config is None:
        config = DEFAULT_CONFIG

    # テンプレート生成（必ず成功する）
    if file_path is not None:
        template = generate_template_tests(
            file_path,
            max_functions=config.max_functions,
            project_root=project_root,
        )
    else:
        # file_path がない場合は、code を一時ファイルに書き込んでパース
        # 簡易実装: code を直接パース
        try:
            tree = ast.parse(code)
            function_names: list[str] = []
            for node in ast.walk(tree):
                if isinstance(node, ast.FunctionDef):
                    function_names.append(node.name)
            function_names = function_names[: config.max_functions]

            template = (
                "# Auto-generated by NexusCore test_generator (template mode)\n\nimport pytest\n\n"
            )
            for func_name in function_names:
                template += f"def test_{func_name}():\n"
                template += f"    # TODO: implement test for {func_name}\n"
                template += '    assert False, "not implemented"\n\n'
        except Exception as e:
            logger.warning(f"Failed to parse code directly: {e}")
            template = f'''# Auto-generated by NexusCore test_generator (template mode)
# NOTE: Failed to parse code. Please write tests manually.

import pytest


def test_auto_generated_test_scaffold_parse_error():
    """Auto-generated test scaffold due to parse error."""
    pytest.skip("Failed to parse code: {e}")
'''

    # LLM 連携（失敗しても template にフォールバック）
    if config.use_llm:
        final_code = _try_generate_tests_with_llm(
            template,
            code,
            config,
            file_path,
            project_root,
            module_path,
        )
    else:
        final_code = template

    # your_module プレースホルダを正しい import パスに置換
    if "your_module" in final_code:
        # module_path が未決定の場合は file_path と project_root から導出
        if module_path is None and file_path is not None and project_root is not None:
            module_path = project_path_to_module_path(project_root, file_path)

        if module_path:
            # "from your_module import" を "from {module_path} import" に置換
            final_code = final_code.replace("from your_module import", f"from {module_path} import")
            # "import your_module" を "import {module_path}" に置換
            final_code = final_code.replace("import your_module", f"import {module_path}")
            # "your_module." を "{module_path}." に置換
            final_code = final_code.replace("your_module.", f"{module_path}.")
        else:
            # module_path が決定できない場合は your_module を削除（コメントアウト）
            final_code = final_code.replace(
                "from your_module import", "# from your_module import  # module path not available"
            )
            final_code = final_code.replace(
                "import your_module", "# import your_module  # module path not available"
            )
            final_code = final_code.replace(
                "your_module.", "# your_module.  # module path not available"
            )

    # 必ず何かしらのコードを返す（例外は投げない）
    return final_code


def generate_and_validate_test_code(
    code: str,
    file_path: Path | None = None,
    project_root: Path | None = None,
    module_path: str | None = None,
) -> tuple[str, bool, str | None, list[str]]:
    """
    テストコードを生成し、検証も行う。

    Args:
        code: テスト対象の Python コード
        file_path: 対象ファイルのパス
        project_root: プロジェクトルート
        module_path: モジュールパス

    Returns:
        (test_code, is_valid, error_message, warnings) のタプル
    """
    # テストコードを生成
    generated = generate_unit_tests(code, file_path, project_root, module_path)

    # Markdown からコードを抽出
    test_code = extract_code_from_markdown(generated)

    # your_module プレースホルダを正しい import パスに置換（generate_unit_tests で既に処理済みだが念のため）
    if "your_module" in test_code:
        # module_path が未決定の場合は file_path と project_root から導出
        if module_path is None and file_path is not None and project_root is not None:
            module_path = project_path_to_module_path(project_root, file_path)

        if module_path:
            # "from your_module import" を "from {module_path} import" に置換
            test_code = test_code.replace("from your_module import", f"from {module_path} import")
            # "import your_module" を "import {module_path}" に置換
            test_code = test_code.replace("import your_module", f"import {module_path}")
            # "your_module." を "{module_path}." に置換
            test_code = test_code.replace("your_module.", f"{module_path}.")
        else:
            # module_path が決定できない場合は your_module を削除（コメントアウト）
            test_code = test_code.replace(
                "from your_module import", "# from your_module import  # module path not available"
            )
            test_code = test_code.replace(
                "import your_module", "# import your_module  # module path not available"
            )
            test_code = test_code.replace(
                "your_module.", "# your_module.  # module path not available"
            )

    # 検証
    is_valid, error_message, warnings = validate_test_code(test_code)

    # 警告をログ出力
    if warnings:
        logger.warning(f"Test code validation warnings: {warnings}")

    # エラーがある場合はフォールバック
    if not is_valid and error_message:
        logger.error(f"Generated test code is invalid: {error_message}")
        if file_path:
            test_code = create_fallback_test_file(file_path, error_message)
            is_valid = True  # フォールバックファイルは有効
            error_message = None

    return test_code, is_valid, error_message, warnings


def generate_tests_for_module(
    module_path: Path,
    output_path: Path | None = None,
    project_root: Path | None = None,
    config: TestGenConfig | None = None,
) -> Path:
    """
    モジュールに対してテストコードを生成し、ファイルに保存する。

    Args:
        module_path: 対象モジュールのパス
        output_path: 出力先パス（None の場合は module_path と同じディレクトリに test_<module_name>.py を作成）
        project_root: プロジェクトルート
        config: 設定（None の場合は DEFAULT_CONFIG を使用）

    Returns:
        生成されたテストファイルのパス
    """
    if config is None:
        config = DEFAULT_CONFIG

    # コードを読み込み
    try:
        code = module_path.read_text(encoding="utf-8", errors="ignore")
    except Exception as e:
        logger.error(f"Failed to read module {module_path}: {e}")
        # フォールバック: 最低限のテストファイルを生成
        if output_path is None:
            output_path = module_path.parent / f"test_{module_path.stem}.py"
        output_path.write_text(
            f'''# Auto-generated by NexusCore test_generator (template mode)
# NOTE: Failed to read module {module_path}. Please write tests manually.

import pytest


def test_auto_generated_test_scaffold_read_error():
    """Auto-generated test scaffold due to read error."""
    pytest.skip("Failed to read module: {e}")
''',
            encoding="utf-8",
        )
        return output_path

    # テストコードを生成
    generated = generate_unit_tests(
        code,
        file_path=module_path,
        project_root=project_root,
        config=config,
    )

    # Markdown からコードを抽出
    test_code = extract_code_from_markdown(generated)

    # 出力パスの決定
    if output_path is None:
        output_path = module_path.parent / f"test_{module_path.stem}.py"

    # ファイルに保存
    output_path.write_text(test_code, encoding="utf-8")
    logger.info(f"Generated test file: {output_path}")

    return output_path


# CLI エントリポイント
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="NexusCore test_generator: Generate pytest test code from Python modules"
    )
    parser.add_argument(
        "module_path",
        type=Path,
        help="Path to the Python module to generate tests for",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None,
        help="Output path for the generated test file (default: test_<module_name>.py in the same directory)",
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=None,
        help="Project root directory (for import path generation)",
    )
    parser.add_argument(
        "--safe-only",
        "--no-llm",
        action="store_true",
        help="Disable LLM and use template mode only",
    )
    parser.add_argument(
        "--enable-llm",
        action="store_true",
        help="Enable LLM (overrides NEXUS_TESTGEN_ENABLE_LLM environment variable)",
    )
    parser.add_argument(
        "--max-functions",
        type=int,
        default=None,
        help="Maximum number of functions to generate tests for (overrides NEXUS_TESTGEN_MAX_FUNCTIONS)",
    )

    args = parser.parse_args()

    # 設定の構築
    config = TestGenConfig(
        use_llm=(
            args.enable_llm if args.enable_llm else (not args.safe_only and DEFAULT_CONFIG.use_llm)
        ),
        max_functions=(
            args.max_functions if args.max_functions is not None else DEFAULT_CONFIG.max_functions
        ),
        seed=None,
    )

    # プロジェクトルートの決定
    project_root = args.project_root
    if project_root is None:
        # モジュールパスから推測（親ディレクトリを辿って setup.py や pyproject.toml を探す）
        current = args.module_path.parent
        while current != current.parent:
            if (current / "setup.py").exists() or (current / "pyproject.toml").exists():
                project_root = current
                break
            current = current.parent

    # テストコードを生成
    try:
        output_path = generate_tests_for_module(
            args.module_path,
            output_path=args.output,
            project_root=project_root,
            config=config,
        )
        print(f"✅ Generated test file: {output_path}")
    except Exception as e:
        logger.error(f"Failed to generate tests: {e}", exc_info=True)
        print(f"❌ Failed to generate tests: {e}")
        exit(1)
