# 📁 test_generator.py
# 📂 保存場所: /src/utils/test_generator.py
"""
test_generator: pytest テストコード生成モジュール

生成方針:
- pytest ベースの関数名（test_ で始まる）
- if __name__ == "__main__": を書かない
- DB 接続を行わない
- ファイル書き込み I/O を行わない（必要なら mock を書くよう明示）
- 危険な操作（subprocess, eval, exec など）を禁止

安定化機能:
- LLM なしでも AST ベースでテンプレート生成可能（safe/template mode）
- LLM エラー時は自動的にテンプレートにフォールバック
- 環境変数で LLM の有効/無効を制御可能
"""

from __future__ import annotations

import ast
import logging
import os
from dataclasses import dataclass
from pathlib import Path

import requests

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None  # type: ignore[assignment]

from nexuscore.utils.test_utils import (
    create_fallback_test_file,
    extract_code_from_markdown,
    project_path_to_module_path,
    validate_test_code,
)

if load_dotenv is not None:
    load_dotenv()
logger = logging.getLogger(__name__)


@dataclass
class TestGenConfig:
    """
    test_generator の設定クラス

    Attributes:
        use_llm: LLM を使用するかどうか（False の場合は template mode のみ）
        max_functions: 1ファイルあたり最大何関数までテスト生成するか
        seed: ランダムシード（将来の拡張用）
    """

    use_llm: bool = True
    max_functions: int = 20
    seed: int | None = None


def _env_flag(name: str, default: bool) -> bool:
    v = os.getenv(name)
    if v is None:
        return default
    return v.lower() not in {"0", "false", "no"}


DEFAULT_CONFIG = TestGenConfig(
    use_llm=_env_flag("NEXUS_TESTGEN_ENABLE_LLM", True),
    max_functions=int(os.getenv("NEXUS_TESTGEN_MAX_FUNCTIONS", "20")),
    seed=None,
)


def _call_minimax(messages: list[dict], temperature: float = 0.3) -> str:
    """Call MiniMax chat completions API via HTTP."""
    api_key = os.getenv("MINIMAX_API_KEY")
    api_base = os.getenv("MINIMAX_API_BASE", "https://api.minimax.chat/v1")
    model = os.getenv("MINIMAX_MODEL", "MiniMax-M2.7")
    if not api_key:
        raise ValueError("MINIMAX_API_KEY environment variable is not set")
    response = requests.post(
        f"{api_base}/chat/completions",
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        json={"model": model, "messages": messages, "temperature": temperature},
        timeout=120,
    )
    response.raise_for_status()
    return response.json()["choices"][0]["message"]["content"]


def generate_template_tests(
    module_path: Path,
    *,
    max_functions: int = 20,
    project_root: Path | None = None,
) -> str:
    """LLMを使わずAST解析だけでpytest用テンプレートを生成する。"""
    try:
        try:
            source_code = module_path.read_text(encoding="utf-8", errors="ignore")
        except (OSError, UnicodeDecodeError) as e:
            logger.warning(f"Failed to read module {module_path}: {e}")
            return f'# Auto-generated test scaffold\nimport pytest\ndef test_read_error():\n    pytest.skip("Failed to read module: {e}")\n'

        try:
            tree = ast.parse(source_code, filename=str(module_path))
        except SyntaxError as e:
            logger.warning(f"Failed to parse module {module_path}: {e}")
            return f'# Auto-generated test scaffold\nimport pytest\ndef test_parse_error():\n    pytest.skip("Failed to parse module: {e}")\n'

        function_names: list[str] = []
        class_methods: list[tuple[str, str]] = []

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                function_names.append(node.name)
            elif isinstance(node, ast.ClassDef):
                for item in node.body:
                    if isinstance(item, ast.FunctionDef):
                        if not item.name.startswith("_"):
                            class_methods.append((node.name, item.name))

        all_functions = function_names[:max_functions]
        all_methods = class_methods[:max_functions]

        if project_root is not None:
            try:
                module_import_path = project_path_to_module_path(project_root, module_path)
            except (ValueError, OSError):
                module_import_path = module_path.stem
        else:
            module_import_path = module_path.stem

        lines = [
            "# Auto-generated by NexusCore test_generator (template mode)",
            "",
            "import pytest",
            "",
        ]

        if module_import_path:
            lines.append(f"from {module_import_path} import *  # NOTE: adjust import path")
        lines.append("")

        for func_name in all_functions:
            lines.append(f"def test_{func_name}():")
            lines.append(f"    # NOTE: implement test for {module_import_path}.{func_name}")
            lines.append('    assert False, "not implemented"')
            lines.append("")

        for class_name, method_name in all_methods:
            test_name = f"test_{class_name}_{method_name}"
            lines.append(f"def {test_name}():")
            lines.append(f"    # NOTE: implement test for {module_import_path}.{class_name}.{method_name}")
            lines.append('    assert False, "not implemented"')
            lines.append("")

        if not all_functions and not all_methods:
            lines.append("def test_auto_generated_test_scaffold_no_functions():")
            lines.append('    """Auto-generated test scaffold (no functions found)."""')
            lines.append('    pytest.skip("No functions found in module")')
            lines.append("")

        return "\n".join(lines)

    except Exception as e:  # noqa: BLE001
        logger.error(f"Unexpected error in generate_template_tests: {e}", exc_info=True)
        return f'# Auto-generated test scaffold\nimport pytest\ndef test_unexpected_error():\n    pytest.skip("Unexpected error: {e}")\n'


def _try_generate_tests_with_llm(
    template_code: str,
    code: str,
    config: TestGenConfig,
    file_path: Path | None = None,
    project_root: Path | None = None,
    module_path: str | None = None,
) -> str:
    """テンプレートをベースにLLMでテストコードを生成。失敗時はtemplate_codeを返す。"""
    if not config.use_llm:
        return template_code

    try:
        if module_path is None and file_path is not None and project_root is not None:
            module_path = project_path_to_module_path(project_root, file_path)

        prompt = f"""次のPythonコードに対して、pytest形式のユニットテストを生成してください。

# 対象コード
```python
{code}
```

# テンプレート（参考）
```python
{template_code}
```

# 絶対守ってほしい制約（必須）
1. pytest ベースの関数名（test_ で始まる）を使用してください
2. if __name__ == "__main__": を書かないでください
3. DB 接続を行わないでください（必要なら mock を使用）
4. ファイル書き込み I/O を行わないでください（必要なら mock を使用）
5. 危険な操作（subprocess, eval, exec, __import__）を絶対に使用しないでください
6. 外部API依存は必ずモック化してください
7. time.sleep は使わないでください
8. ランダム値は固定してください

# 出力形式（必須）
pytest テストコードを生成してください。コードブロック（```python ... ```）で囲んで出力してください。
"""

        generated_code = _call_minimax(
            [
                {
                    "role": "system",
                    "content": "あなたは優秀なPythonのテストエンジニアです。安全性と品質を最優先に、pytest形式のテストコードを生成します。",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
        )

        if generated_code:
            return generated_code
        else:
            logger.warning("LLM returned empty response, falling back to template")
            return template_code

    except ValueError as e:
        logger.warning(f"MiniMax API key not configured: {e}, falling back to template")
        return template_code
    except Exception as e:  # noqa: BLE001
        logger.warning(f"LLM generation failed: {e}, falling back to template", exc_info=True)
        return template_code


def generate_unit_tests(
    code: str,
    file_path: Path | None = None,
    project_root: Path | None = None,
    module_path: str | None = None,
    config: TestGenConfig | None = None,
) -> str:
    """Pythonコードに対してpytest形式のユニットテストを生成。LLM失敗時はテンプレートにフォールバック。"""
    if config is None:
        config = DEFAULT_CONFIG

    if file_path is not None:
        template = generate_template_tests(
            file_path,
            max_functions=config.max_functions,
            project_root=project_root,
        )
    else:
        try:
            tree = ast.parse(code)
            function_names: list[str] = []
            for node in ast.walk(tree):
                if isinstance(node, ast.FunctionDef):
                    function_names.append(node.name)
            function_names = function_names[: config.max_functions]

            template = "# Auto-generated by NexusCore test_generator (template mode)\n\nimport pytest\n\n"
            for func_name in function_names:
                template += f"def test_{func_name}():\n"
                template += f"    # NOTE: implement test for {func_name}\n"
                template += '    assert False, "not implemented"\n\n'
        except SyntaxError as e:
            logger.warning(f"Failed to parse code directly: {e}")
            template = '# Auto-generated test scaffold\nimport pytest\ndef test_parse_error():\n    pytest.skip("Failed to parse code")\n'

    if config.use_llm:
        final_code = _try_generate_tests_with_llm(
            template, code, config, file_path, project_root, module_path,
        )
    else:
        final_code = template

    if "your_module" in final_code:
        if module_path is None and file_path is not None and project_root is not None:
            module_path = project_path_to_module_path(project_root, file_path)

        if module_path:
            final_code = final_code.replace("from your_module import", f"from {module_path} import")
            final_code = final_code.replace("import your_module", f"import {module_path}")
            final_code = final_code.replace("your_module.", f"{module_path}.")
        else:
            final_code = final_code.replace("from your_module import", "# from your_module import  # module path not available")
            final_code = final_code.replace("import your_module", "# import your_module  # module path not available")
            final_code = final_code.replace("your_module.", "# your_module.  # module path not available")

    return final_code


def generate_and_validate_test_code(
    code: str,
    file_path: Path | None = None,
    project_root: Path | None = None,
    module_path: str | None = None,
) -> tuple[str, bool, str | None, list[str]]:
    """テストコードを生成し、検証も行う。"""
    generated = generate_unit_tests(code, file_path, project_root, module_path)
    test_code = extract_code_from_markdown(generated)

    if "your_module" in test_code:
        if module_path is None and file_path is not None and project_root is not None:
            module_path = project_path_to_module_path(project_root, file_path)
        if module_path:
            test_code = test_code.replace("from your_module import", f"from {module_path} import")
            test_code = test_code.replace("import your_module", f"import {module_path}")
            test_code = test_code.replace("your_module.", f"{module_path}.")
        else:
            test_code = test_code.replace("from your_module import", "# from your_module import  # module path not available")
            test_code = test_code.replace("import your_module", "# import your_module  # module path not available")
            test_code = test_code.replace("your_module.", "# your_module.  # module path not available")

    is_valid, error_message, warnings = validate_test_code(test_code)
    if warnings:
        logger.warning(f"Test code validation warnings: {warnings}")
    if not is_valid and error_message:
        logger.error(f"Generated test code is invalid: {error_message}")
        if file_path:
            test_code = create_fallback_test_file(file_path, error_message)
            is_valid = True
            error_message = None

    return test_code, is_valid, error_message, warnings


def generate_tests_for_module(
    module_path: Path,
    output_path: Path | None = None,
    project_root: Path | None = None,
    config: TestGenConfig | None = None,
) -> Path:
    """モジュールに対してテストコードを生成しファイルに保存。"""
    if config is None:
        config = DEFAULT_CONFIG

    try:
        code = module_path.read_text(encoding="utf-8", errors="ignore")
    except (OSError, UnicodeDecodeError) as e:
        logger.error(f"Failed to read module {module_path}: {e}")
        if output_path is None:
            output_path = module_path.parent / f"test_{module_path.stem}.py"
        output_path.write_text(
            f'# Auto-generated test scaffold\nimport pytest\ndef test_read_error():\n    pytest.skip("Failed to read module: {e}")\n',
            encoding="utf-8",
        )
        return output_path

    generated = generate_unit_tests(code, file_path=module_path, project_root=project_root, config=config)
    test_code = extract_code_from_markdown(generated)

    if output_path is None:
        output_path = module_path.parent / f"test_{module_path.stem}.py"

    output_path.write_text(test_code, encoding="utf-8")
    logger.info(f"Generated test file: {output_path}")
    return output_path


# CLI エントリポイント
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="NexusCore test_generator")
    parser.add_argument("module_path", type=Path, help="Path to the Python module")
    parser.add_argument("-o", "--output", type=Path, default=None, help="Output path")
    parser.add_argument("--project-root", type=Path, default=None, help="Project root directory")
    parser.add_argument("--safe-only", "--no-llm", action="store_true", help="Disable LLM")
    parser.add_argument("--enable-llm", action="store_true", help="Enable LLM")
    parser.add_argument("--max-functions", type=int, default=None, help="Max functions")

    args = parser.parse_args()

    config = TestGenConfig(
        use_llm=(args.enable_llm if args.enable_llm else (not args.safe_only and DEFAULT_CONFIG.use_llm)),
        max_functions=(args.max_functions if args.max_functions is not None else DEFAULT_CONFIG.max_functions),
        seed=None,
    )

    project_root = args.project_root
    if project_root is None:
        current = args.module_path.parent
        while current != current.parent:
            if (current / "setup.py").exists() or (current / "pyproject.toml").exists():
                project_root = current
                break
            current = current.parent

    try:
        output_path = generate_tests_for_module(args.module_path, output_path=args.output, project_root=project_root, config=config)
        print(f"✅ Generated test file: {output_path}")
    except Exception as e:  # noqa: BLE001
        logger.error(f"Failed to generate tests: {e}", exc_info=True)
        print(f"❌ Failed to generate tests: {e}")
        exit(1)
