# ==============================================================================
# フォルダ: src/agents
# ファイル名: postmortem_agent.py
# メモ: 【思考プロセス強化版】生成するFKBのsolution_patternが、
#      テストを完全にパスさせるための、より包括的で完全な解決策になるよう、
#      プロンプトの思考プロセスを大幅に強化。
# ==============================================================================
import json
import re
import logging
from .base_agent import BaseAgent

class PostmortemAgent(BaseAgent):
    SYSTEM_PROMPT = """
あなたは、非常に経験豊富なソフトウェア開発者であり、根本原因分析（RCA）の専門家です。
あなたの仕事は、他のAIエージェントが解決に失敗したテストエラーの完全なコンテキストを分析し、
そのエラーを将来解決するための「知識」をJSON形式で生成することです。
"""

    def analyze_failure_and_suggest_fkb_entry(
        self,
        error_log: str,
        source_code: str,
        test_code: str,
        source_file_path: str,
        test_file_path: str
    ) -> dict | None:
        """
        未知のエラーを分析し、fkb_local.jsonに追加すべき新しいエントリを提案する。
        成功した場合は辞書を、失敗した場合はNoneを返す。
        """
        self.logger.info(f"Analyzing failed test to generate new FKB entry (source={source_file_path}, test={test_file_path})")

        # ▼▼▼▼▼ ここからが最重要修正点 ▼▼▼▼▼
        prompt = f"""
# 状況
我々のAI開発システムが、以下のテストエラーの自己修復に失敗しました。
原因は、故障知識ベース（FKB）に、このエラーを解決するためのルールが存在しなかったことです。
あなたの任務は、この失敗事例を分析し、FKBに追加すべき新しい知識エントリを1つ生成することです。

# 分析対象データ
---
## 1. 失敗したテストのエラーログ
```
{error_log}
```
---
## 2. エラーが発生したソースコード (`{source_file_path}`)
```python
{source_code}
```
---
## 3. 失敗したテストコード (`{test_file_path}`)
```python
{test_code}
```
---

# あなたへの厳格な指示
上記の情報に基づき、以下の思考プロセスに従って、FKBエントリを生成してください。

## 思考プロセス
1.  **根本原因の特定**: エラーログとコードを注意深く読み、バグの根本原因を特定せよ。（例：「テストコードが、ネストされた関数を直接インポートしようとしている」）
2.  **エラーシグネチャの一般化**: エラーログから、この種のエラーを将来確実に捕捉できる、汎用的な正規表現（regex）を `error_signature` として考案せよ。
3.  **完全な解決策の考案**: このバグを修正し、**テストを完全にパスさせる**には、どのファイルをどのように変更する必要があるかを具体的に考えよ。
    -   例えば、`ImportError`を修正する場合、`import`文の修正だけでなく、そのインポートを利用している箇所の**関数名**も修正する必要があるかもしれない。
    -   例えば、ソースコードの関数名を変更する場合、テストコードの呼び出し箇所も変更する必要がある。
    -   この具体的な修正を、`llm_diagnose_and_fix`の`instruction`として記述せよ。
4.  **最終的なJSONの構築**: 上記の分析結果を基に、`id`, `error_signature`, `cause`, `target`, `solution_pattern`, `description` を持つ、単一のJSONオブジェクトを生成せよ。

## `solution_pattern` の詳細なルール
- `solution_pattern` は、必ず "type" キーを持つ **JSONオブジェクト（辞書）**でなければならない。
- `type` が `"llm_diagnose_and_fix"` の場合: `"instruction"` キーに、**テストを完全にパスさせるための、包括的な修正指示**を記述せよ。

## JSON出力例
```json
{{
  "id": "FKB-SUGGESTION-0001",
  "error_signature": "ImportError: cannot import name 'add'",
  "cause": "テストコードが、ネストされた関数や、誤った名前の関数を直接インポートしようとしている。",
  "target": "test_file",
  "solution_pattern": {{
    "type": "llm_diagnose_and_fix",
    "instruction": "The test failed with an ImportError. Analyze the source code to find the correct way to access the intended function. Modify the test code to import the parent function and then call it to get the nested function, or fix the imported function name if it's a simple typo. The goal is to make the test pass."
  }},
  "description": "ネストされた関数やタイポによる不正なインポートが原因のエラーを、テストコード側を修正することで解決する知識。"
}}
```

# 絶対的な出力ルール
- **生成したJSONオブジェクトのみ**を出力すること。
- 説明、前置き、その他のテキストは一切含めてはならない。
- `id` は `"FKB-SUGGESTION-XXXX"` の形式とせよ。
- `cause` と `description` は、日本語で簡潔に記述すること。
- JSONは必ず `{{` で始まり、 `}}` で終わる単一のオブジェクトであること。
"""
        # ▲▲▲▲▲ ここまでが最重要修正点 ▲▲▲▲▲
        try:
            response_str = self._call_llm(prompt, self.SYSTEM_PROMPT, temperature=0.3, as_json=True)
            match = re.search(r'\{.*\}', response_str, re.DOTALL)
            if not match:
                self.logger.error(f"LLM response does not contain a JSON object. Raw response:\n{response_str}")
                return None
            
            json_str = match.group(0)
            suggestion = json.loads(json_str)
            self.logger.info("Successfully generated a new FKB suggestion.")
            return suggestion

        except json.JSONDecodeError as e:
            self.logger.error(f"Invalid JSON generated by LLM: {e}. Raw response:\n{response_str}")
            return None
        except Exception as e:
            self.logger.error(f"An unexpected error occurred in PostmortemAgent: {e}", exc_info=True)
            return None
