"""
test_generator の軽量 E2E テスト

サンプルプロジェクト内の関数に対して、テストコードを生成し、
最低限「pytest でインポート可能なテストファイル」が得られること。
生成されたテストコードが実際に pytest で実行可能であることも確認する。
"""

from __future__ import annotations

import os
import pytest
import subprocess
import sys
import importlib.util
from pathlib import Path

try:
    from nexuscore.utils.test_generator import (
        generate_unit_tests,
        generate_and_validate_test_code,
    )
    from nexuscore.utils.test_utils import (
        validate_test_code,
        extract_code_from_markdown,
        project_path_to_module_path,
    )
    HAS_TEST_GENERATOR = True
except ImportError:
    HAS_TEST_GENERATOR = False
    generate_unit_tests = None  # type: ignore
    generate_and_validate_test_code = None  # type: ignore


@pytest.mark.skipif(not HAS_TEST_GENERATOR, reason="Test generator not available")
@pytest.mark.skipif(
    not Path(".env").exists() or "OPENAI_API_KEY" not in Path(".env").read_text(),
    reason="OPENAI_API_KEY not configured (skipping LLM-based test)"
)
def test_test_generator_creates_runnable_pytest_file(sample_project_dir, tmp_path):
    """
    サンプルプロジェクト内の関数に対してテストコードを生成し、
    生成されたテストファイルを pytest で実行してエラーにならないことを確認する。
    """
    out_dir = tmp_path / "generated_tests"
    out_dir.mkdir()

    # module_b.py の内容を取得
    module_b_path = sample_project_dir / "module_b.py"
    if not module_b_path.exists():
        pytest.skip("module_b.py not found in sample project")

    code = module_b_path.read_text(encoding="utf-8")

    # テストコードを生成
    try:
        generated_test_code = generate_unit_tests(code)
    except Exception as e:
        pytest.skip(f"Test generation failed (likely LLM API issue): {e}")

    # 生成されたコードからテストファイルを抽出（簡易版）
    # 実際の実装では、generate_unit_tests がファイルを直接書き込む可能性もある
    if "```python" in generated_test_code:
        # Markdown コードブロックから抽出
        lines = generated_test_code.split("\n")
        in_code_block = False
        test_lines = []
        for line in lines:
            if "```python" in line:
                in_code_block = True
                continue
            if "```" in line and in_code_block:
                break
            if in_code_block:
                test_lines.append(line)
        test_code = "\n".join(test_lines)
    else:
        test_code = generated_test_code

    # テストファイルを保存
    test_file = out_dir / "test_module_b.py"
    test_file.write_text(test_code, encoding="utf-8")

    # 何かしら test_*.py が生成されていること
    test_files = list(out_dir.glob("test_*.py"))
    assert test_files, "No test files generated by TestGenerator"

    # 生成されたコードを検証
    test_code = test_file.read_text(encoding="utf-8")
    is_valid, error_message, warnings = validate_test_code(test_code)
    
    # 構文エラーがある場合は失敗
    if not is_valid:
        pytest.fail(f"Generated test code has syntax errors: {error_message}")
    
    # 警告があればログに記録
    if warnings:
        for warning in warnings:
            pytest.fail(f"Generated test code has warnings: {warning}")

    # importlib でインポート可能か確認
    try:
        spec = importlib.util.spec_from_file_location("test_module_b", test_file)
        if spec and spec.loader:
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            # インポート成功
    except Exception as import_error:
        pytest.fail(f"Generated test file is not importable: {import_error}")

    # 実際に pytest を実行（小規模サンプルのみ）
    # 環境変数でスキップ可能にする
    if os.getenv("SKIP_PYTEST_EXECUTION", "0") == "1":
        pytest.skip("Pytest execution skipped (SKIP_PYTEST_EXECUTION=1)")
    
    try:
        cmd = [sys.executable, "-m", "pytest", "-q", str(out_dir), "--tb=short"]
        result = subprocess.run(
            cmd,
            cwd=str(sample_project_dir),
            capture_output=True,
            text=True,
            timeout=30,
        )
        # エラーでもインポートエラーでなければ許容（LLM 生成の品質は保証しない）
        if result.returncode != 0:
            # インポートエラーの場合は失敗
            if "ImportError" in result.stderr or "ModuleNotFoundError" in result.stderr:
                pytest.fail(f"Generated tests have import errors:\n{result.stderr}")
            # その他のエラー（アサーション失敗など）は許容（ログに記録）
            print(f"Pytest execution completed with return code {result.returncode}")
            print(f"Stdout: {result.stdout}")
            print(f"Stderr: {result.stderr}")
    except subprocess.TimeoutExpired:
        pytest.skip("Test execution timed out (likely LLM generation issue)")
    except Exception as e:
        # インポート可能であることは既に確認済みなので、pytest 実行エラーは許容
        print(f"Pytest execution failed (but import succeeded): {e}")


@pytest.mark.skipif(not HAS_TEST_GENERATOR, reason="Test generator not available")
@pytest.mark.skipif(
    not Path(".env").exists() or "OPENAI_API_KEY" not in Path(".env").read_text(),
    reason="OPENAI_API_KEY not configured (skipping LLM-based test)"
)
def test_test_generator_validation(sample_project_dir, tmp_path):
    """生成されたテストコードの検証ロジックが動作することを確認"""
    module_b_path = sample_project_dir / "module_b.py"
    if not module_b_path.exists():
        pytest.skip("module_b.py not found in sample project")
    
    code = module_b_path.read_text(encoding="utf-8")
    
    # 検証付きでテストコードを生成
    try:
        test_code, is_valid, error_message, warnings = generate_and_validate_test_code(
            code,
            file_path=module_b_path,
            project_root=sample_project_dir,
        )
    except Exception as e:
        pytest.skip(f"Test generation failed (likely LLM API issue): {e}")
    
    # 検証結果を確認
    assert is_valid, f"Generated test code should be valid: {error_message}"
    
    # 警告があれば確認
    if warnings:
        print(f"Validation warnings: {warnings}")


@pytest.mark.skipif(not HAS_TEST_GENERATOR, reason="Test generator not available")
def test_project_path_to_module_path():
    """project_path_to_module_path ユーティリティが正しく動作することを確認"""
    from nexuscore.utils.test_utils import project_path_to_module_path
    
    project_root = Path("/project")
    file_path = Path("/project/src/foo/bar.py")
    
    module_path = project_path_to_module_path(project_root, file_path)
    assert module_path == "src.foo.bar"
    
    # プロジェクト外のファイル
    external_path = Path("/other/project/file.py")
    module_path = project_path_to_module_path(project_root, external_path)
    assert module_path == "file"  # ファイル名のみ

